export const NFT_FETCH_SUCCESS = 'NFT_FETCH_SUCCESS';
export const NFT_FETCH_FAIL = 'NFT_FETCH_FAIL';
export const NFT_UPDATE_SUCCESS = 'NFT_UPDATE_SUCCESS';
export const NFT_UPDATE_FAIL = 'NFT_UPDATE_FAIL';
export const NFT_DELETE_SUCCESS = 'NFT_DELETE_SUCCESS';
export const NFT_DELETE_FAIL = 'NFT_DELETE_FAIL';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
